name: wall
description: wall app

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # - - - https://pub.dev/packages/xxx/ - - -
  # 网络请求
  dio: ^4.0.0
  # 全局数据存储，类Vuex
  provider: ^6.0.0
  # bloc
  flutter_bloc: ^7.3.0
  # 本地键值对存储
  shared_preferences: ^2.0.8
  # 权限管理
  permission_handler: ^8.1.6
  # 路由
  fluro: ^2.0.3
  # 设备信息
  device_info: ^2.0.2
  # 极光推送
  jpush_flutter: ^2.1.5
  # umeng分析
  umeng_analytics_plugin: ^1.0.3
  # apk安装, ios跳转, 不支持embedded2
  install_plugin: ^2.0.1
  # flutter 长连接
  web_socket_channel: ^2.1.0
  # 事件总线
  event_bus: ^2.0.0
  # ws
  stomp_dart_client: ^0.4.3

  # 网页
  webview_flutter: ^2.1.2
  # 图片缓存
  cached_network_image: ^3.1.0
  # 地区选择
  city_pickers: ^1.0.1
  # 小红点
  badges: ^2.0.1
  # 文本溢出等
  extended_text: ^7.0.0
  # 可折叠字体
  expandable: ^5.0.1
  # flutter 工具类, 包含SharedPreferences Util, Screen Util, Directory Util, Widget Util, Image Util
  flustars: ^2.0.1
  # sp_util从flustars分拆成单独的库, 可以直接引用
  sp_util: ^2.0.3
  # 像素
  flutter_screenutil: ^5.0.0+2
  # toast
  fluttertoast: ^8.0.8
  # 轮播图
  flutter_swiper: ^1.1.6
  # 加载动画
  flutter_spinkit: ^5.1.0
  # 键盘增强工具
  keyboard_actions: ^3.4.4
  # 动画字体
  animated_text_kit: ^4.2.1
  # 图片选择
  image_picker: ^0.8.4+2
  # 图片裁剪
  image_cropper: ^1.4.1
  # 图片保存
  image_gallery_saver: ^1.7.0
  # 透明图片
  transparent_image: ^2.0.0
  # svg
  flutter_svg: ^0.22.0
  # 下拉刷新
  pull_to_refresh: ^2.0.0
  flutter_easyrefresh: ^2.2.1
  # 图像预览
  photo_view: ^0.12.0
  # flare动画
  flare_flutter: ^3.0.2
  # 日期选择
  flutter_datetime_picker: ^1.5.1
  # 缓存管理
  flutter_cache_manager: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0


  # model序列化
  json_annotation: ^4.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/flrs/
    - assets/images/
    - assets/images/guide/
    - assets/icons/
    - assets/icons/common/
    - assets/svg/
    - assets/svg/crm/
    - assets/svg/common/
    - assets/svg/nav/
    - assets/svg/setting/
    - assets/svg/noti/


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
